Build and release workflows with tooling
bitwarden/terraform-provider-bitwarden-sm pull request #21
Opened 2024-08-28 08:51 UTC by tgraupne

This PR contains updated to our GitHUb Actions Workflows in preparation of the release of our terraform provider.
Example executions of the release-workflow triggered by pushing a tag can be found here:

https://github.com/bitwarden/terraform-provider-bitwarden-sm/actions/runs/10579959606

We followed hashicorps documentation about the manual release preparation:
https://developer.hashicorp.com/terraform/registry/providers/publishing#manually-preparing-a-release

The following things are still open:

we need to setup a signing key in order to sign the [hashes of our binaries](https://developer.hashicorp.com/terraform/registry/providers/publishing#signing-in)
we need to decide if we can use large hosted runners in GitHub Actions in order to provide a native ubuntu environment to build arm64 binaries

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-08-29 09:50 UTC, tgraupne commented
Hi @withinfocus, thanks a lot for your feedback. I hope I was able to address all the remarks you made. There is just open follow-up question from my side regarding the the `check-run` step in the `release` workflow.

2025-01-22 12:55 UTC, michalchecinski commented
Closed and re-opened the PR to fire a new workflow linter. @tgraupne, please also fix the things indicated by it: https://github.com/bitwarden/terraform-provider-bitwarden-sm/actions/runs/12908630218/job/35994555617?pr=21

2025-02-02 20:55 UTC, tgraupne commented
Hi @michalchecinski, I tried to incorporate all of your feedback and I create a little miro board showing the implemented GitHub Actions workflows. With that, I am trying to make sure that there are nor misunderstandings in the process we'd like to implement together. I am looking forward to your feedback.

[Bitwarden Release Process.pdf](https://github.com/user-attachments/files/18633897/Bitwarden.Release.Process.pdf)

2025-02-05 10:52 UTC, michalchecinski requested changes

2025-02-05 10:52 UTC, michalchecinski commented on .github/workflows/release.yml
> +          merge-multiple: true
So, @tgraupne could you delete the `Download Artifacts` step (lines 22-27)?

The one below (lines 29-35) is the one that we want to keep.

2025-02-05 10:52 UTC, michalchecinski commented on .github/workflows/build.yml
> +    uses: bitwarden/gh-actions/.github/workflows/check-run.yml@main
Could you remove this step @tgraupne ?

2025-02-05 11:02 UTC, michalchecinski approved these changes

2025-02-05 13:25 UTC, tangowithfoxtrot approved these changes

2025-02-05 13:56 UTC, withinfocus approved these changes
I don't want to hold anything up for merging. Can iterate if needed later and BRE really owns these flows.

2025-02-05 13:56 UTC, merged